apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: dqm-square-mirror-sc
  namespace: dqm
provisioner: manila-provisioner
parameters:
  type: "Meyrin CephFS"
  zones: nova
  osSecretName: os-trustee
  osSecretNamespace: kube-system
  protocol: CEPHFS
  backend: csi-cephfs
  csi-driver: cephfs.csi.ceph.com
  osShareID: 06dce396-d669-43f6-b115-2327052e79de 
  osShareAccessID: 9eeeeb23-0de7-42e1-a286-89469f4fda60 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dqm-square-mirror-pvc
  namespace: dqm
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2G
  storageClassName: dqm-square-mirror-sc
