apiVersion: v1
kind: PersistentVolume
metadata:
  name: dqm-square-mirror-testbed
  namespace: dqm
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 2G
  csi:
    driver: cephfs.manila.csi.openstack.org
    volumeHandle: 06dce396-d669-43f6-b115-2327052e79de
    nodeStageSecretRef:
      name: os-trustee
      namespace: kube-system
    nodePublishSecretRef:
      name: os-trustee
      namespace: kube-system
    volumeAttributes:
      shareID: 06dce396-d669-43f6-b115-2327052e79de
      shareAccessID: 9eeeeb23-0de7-42e1-a286-89469f4fda60
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dqm-square-mirror-pvc
  namespace: dqm
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2G
  storageClassName: ""
  volumeName: dqm-square-mirror-testbed
