apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: dqm-square-mirror-sc
  namespace: dqm
provisioner: manila-provisioner
parameters:
  type: "Meyrin CephFS"
  zones: nova
  osSecretName: os-trustee
  osSecretNamespace: kube-system
  protocol: CEPHFS
  backend: csi-cephfs
  csi-driver: cephfs.csi.ceph.com
  osShareID: 017ddf48-18c1-4179-af0b-1af590e2cc84
  osShareAccessID: fb219e09-c149-4b68-835e-5140f30093ff
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dqm-square-mirror-pvc
  namespace: dqm
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10G
  storageClassName: dqm-square-mirror-sc
