apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: default-share
  namespace: default
provisioner: manila-provisioner
parameters:
  type: "Meyrin CephFS"
  zones: nova
  osSecretName: os-trustee
  osSecretNamespace: kube-system
  protocol: CEPHFS
  backend: csi-cephfs
  csi-driver: cephfs.csi.ceph.com
  osShareID: 97303f7a-23a9-4060-914c-132d75cd279d
  osShareAccessID: cd018975-0a75-4da0-8077-b91580d85201 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-cephfs-claim-prod-default
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 300G
  storageClassName: default-share
