apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: ms-output-share
  namespace: dmwm
provisioner: manila-provisioner
parameters:
  type: "Meyrin CephFS"
  zones: nova
  osSecretName: os-trustee
  osSecretNamespace: kube-system
  protocol: CEPHFS
  backend: csi-cephfs
  csi-driver: cephfs.csi.ceph.com
  osShareID: afa7ae89-9724-40ce-8d09-44006d37e134
  osShareAccessID: 035f6885-f2e0-4ef5-ad6a-753d53ba0c82
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ms-output-claim
  namespace: dmwm
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 25G
  storageClassName: ms-output-share
