apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-dqmgui 
spec:
  storageClassName: sc-cinder-volume-claim
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 25Gi
  csi:
    driver: cinder.csi.openstack.org
    fsType: ext4
    # This is how csi-cinder knows how to find the volume.
    volumeHandle: f8b6a2c0-8a95-47e4-bde3-69db640ff5f9
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dqmgui
  namespace: dqm 
spec:
  # The class must be the same as in the PV
  storageClassName: sc-cinder-volume-claim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # same for storage
      storage: 25Gi
